### ISSUE TITLE
Binder url generated in HTML includes org "cli"

### ISSUE THREAD

**Issue by najuzilu** [ExecutableBookProject/sphinx-book-theme#25]
The binder button in the local `html` files points to this binder_url: https://mybinder.org/v2/gh/ExecutableBookProject/cli/master?filepath=/docs/*.ipynb.

`cli` should be the replaced with the updated `org` var. From what I can tell `add_binder_url()` in `sphinx_book_theme/__init__.py` works fine.

**Comment by najuzilu** [comment]
Here's an example of a current binder_url which does not work:
`https://mybinder.org/v2/gh/ExecutableBookProject/quantecon-example/master?filepath=docs/functions.ipynb`

It should instead be:
`https://mybinder.org/v2/gh/ExecutableBookProject/quantecon-example master?filepath=book%2Fdocs%2Ffunctions.ipynb`

Filepath should be updated to include book path e.g. `book/docs/`

**Comment by choldgraf** [comment]
hmm can you give a link to the repository configuration file? I think that `book_path` should be `book/docs/` and it should work, no?

**Comment by najuzilu** [comment]
I misunderstood what `book_path` stands for. Thanks @choldgraf

**Comment by choldgraf** [comment]
What did you think it meant? Is there a way we could improve this in the docs?
