### ISSUE TITLE
Blockquote vertical line not rendering on html

### ISSUE THREAD

**Issue by najuzilu** [ExecutableBookProject/sphinx-book-theme#26]
The lightgrey vertical line in this blockquotes does not render locally or in the published version.

<img width="842" alt="Screen Shot 2020-03-30 at 12 41 15 AM" src="https://user-images.githubusercontent.com/33075058/77850976-d9b18b00-7221-11ea-95f7-1b929cb7e6e7.png">

**Comment by choldgraf** [comment]
I think that's just how the css is right now. Do you think we need a vertical line for blockquote?

**Comment by najuzilu** [comment]
I was looking at [this example](https://www.textbook.ds100.org/ch/04/eda_intro.html) a few days ago which is why I thought the missing vertical line was a bug. I like the visual distinction with the vertical line that indicates the blockquote but if it's not an easy fix we can worry about this later.  :-)

**Comment by najuzilu** [comment]
@choldgraf I'll close this since you've already taken care if it
