### ISSUE TITLE
Add styling to executed outputs

### ISSUE THREAD

**Issue by najuzilu** [ExecutableBookProject/sphinx-book-theme#32]
I think it might be helpful to add styling around executed outputs - maybe a cell that looks like the code input but lighter? I'm open to other ideas.

Also, some of the executed outputs are aligned in the middle. I think they should be aligned to the left, similar to the rest of the executed outputs.
<img width="798" alt="Screen Shot 2020-03-30 at 2 59 09 PM" src="https://user-images.githubusercontent.com/33075058/78024836-c67af880-73a4-11ea-91a6-d61f8ec7ebbb.png">

**Comment by choldgraf** [comment]
I agree - actually currently we already do this, but only for some kinds of outputs. E.g. a text output renders like:

![image](https://user-images.githubusercontent.com/1839645/78038136-54150480-7321-11ea-9de4-4f07bdffb153.png)

while an image doesn't render with the grey background. My thinking was that images usually "pop" enough that it's clear they're attached to whatever came above...you think it'd be better to have a background to them?

And for the math, I don't have an intuition for whether it's better to the left or the middle. Maybe @jstac or @mmcky could weigh in on that? I could try to snap code-cell math to the left if all agree it makes sense that way

**Comment by najuzilu** [comment]
I agree with you regarding images. I was referring primarily to math output.

**Comment by choldgraf** [comment]
yeah - I agree w/ the math output - it should be distinguishable from the `{math}` directive output

**Comment by jstac** [comment]
While display math in markdown should be in the middle -- as it is now -- I can see why @najuzilu feels surprised that this generated math is not on the left, like text output.  I guess that would be my mild preference too.

**Comment by choldgraf** [comment]
@jstac thanks for the input - I think a reasonable first step is "outputs should behave however they do in the notebook" so that we don't surprise people

**Comment by choldgraf** [comment]
math outputs fixed here: https://github.com/ExecutableBookProject/MyST-NB/pull/115 👍

**Comment by jstac** [comment]
Nice work, thanks @choldgraf :+1:
